import { defaultAppSettings } from './domain';
import type {
  EventRecord,
  FraudFlagRecord,
  PayoutSplitRecord,
  ResaleListingRecord,
  TicketRecord,
  TransferAuditRecord,
} from '../apps/shared/lib/types';
import { calculateResaleLimit } from '../apps/shared/lib/pricing';
import {
  computeTransferEligibility,
  createTransferAudit,
  executeTransfer,
  resolveEventMarketplaceSettings,
} from './transfers';

/** Marketplace state snapshot required to create or settle listings. */
export interface MarketplaceState {
  /** Persisted resale listings. */
  listings: ResaleListingRecord[];
  /** Auditable payout split records. */
  payoutSplits: PayoutSplitRecord[];
  /** Transfer and royalty audit trail. */
  auditLog: TransferAuditRecord[];
  /** Fraud flags emitted by marketplace and scanner controls. */
  fraudFlags: FraudFlagRecord[];
}

/** Result of creating a resale listing after validation. */
export interface CreateResaleListingResult {
  /** Updated ticket flagged for sale or pending approval. */
  ticket: TicketRecord;
  /** Newly created marketplace listing. */
  listing: ResaleListingRecord;
  /** Audit records generated by the listing request. */
  auditRecords: TransferAuditRecord[];
  /** Fraud flags generated while evaluating the request. */
  fraudFlags: FraudFlagRecord[];
}

/** Result of settling a resale purchase with full payout accounting. */
export interface BuyResaleTicketResult {
  /** Updated ticket after ownership transfer. */
  ticket: TicketRecord;
  /** Listing after settlement. */
  listing: ResaleListingRecord;
  /** Auditable payout records for seller and royalties. */
  payoutSplits: PayoutSplitRecord[];
  /** Audit records created by the purchase. */
  auditRecords: TransferAuditRecord[];
  /** Fraud flags generated while evaluating the purchase. */
  fraudFlags: FraudFlagRecord[];
}

/** Input required to list a ticket for resale. */
export interface CreateResaleListingInput {
  /** Event that owns the ticket. */
  event: EventRecord;
  /** Ticket being listed. */
  ticket: TicketRecord;
  /** Seller user id. */
  sellerId: string;
  /** Current seller wallet, if linked. */
  sellerWallet: string | null;
  /** Requested sale price. */
  salePrice: number;
  /** Current marketplace state. */
  marketplace: MarketplaceState;
  /** Current timestamp. */
  now?: number;
}

/** Input required to buy a listed resale ticket. */
export interface BuyResaleTicketInput {
  /** Event that owns the ticket. */
  event: EventRecord;
  /** Ticket being purchased. */
  ticket: TicketRecord;
  /** Listing being settled. */
  listing: ResaleListingRecord;
  /** Buyer user id. */
  buyerId: string;
  /** Buyer wallet, if linked. */
  buyerWallet: string | null;
  /** Current marketplace state. */
  marketplace: MarketplaceState;
  /** Current timestamp. */
  now?: number;
}

/**
 * Creates a resale listing after enforcing price rules, transfer policy, and fraud controls.
 */
export function createResaleListing(
  input: CreateResaleListingInput,
): CreateResaleListingResult {
  const now = input.now ?? Date.now();

  if (input.ticket.ownerId !== input.sellerId) {
    throw new Error('Only the ticket owner can create a resale listing');
  }

  if (input.ticket.isForSale) {
    throw new Error('Ticket is already listed for resale');
  }

  const eligibility = computeTransferEligibility({
    event: input.event,
    ticket: input.ticket,
    actorUserId: input.sellerId,
    auditLog: input.marketplace.auditLog,
    fraudFlags: input.marketplace.fraudFlags,
    now,
  });

  if (eligibility.blockedReasons.length > 0) {
    throw new Error(eligibility.blockedReasons[0]);
  }

  const salePrice = validateResalePrice(input.event, input.ticket, input.salePrice, now);
  const listingId = `listing_${now}_${Math.random().toString(36).slice(2, 8)}`;
  const listing: ResaleListingRecord = {
    id: listingId,
    ticketId: input.ticket.id,
    eventId: input.event.id,
    sellerId: input.sellerId,
    sellerWallet: input.sellerWallet,
    askPrice: salePrice,
    currency: 'usd',
    status: 'active',
    approvalStatus: eligibility.requiresApproval ? 'pending' : 'not_required',
    createdAt: now,
    updatedAt: now,
    soldAt: null,
    buyerId: null,
  };

  const nextTicket: TicketRecord = {
    ...input.ticket,
    isForSale: !eligibility.requiresApproval,
    salePrice,
    pendingTransferApproval: eligibility.requiresApproval,
  };

  const auditRecords = [
    createTransferAudit({
      eventId: input.event.id,
      ticketId: input.ticket.id,
      action: 'resale_listed',
      actorUserId: input.sellerId,
      listingId,
      metadata: {
        approvalStatus: listing.approvalStatus,
        askPrice: salePrice.toFixed(2),
      },
      now,
    }),
  ];

  const newFraudFlags = eligibility.fraudFlags.slice(input.marketplace.fraudFlags.length);
  auditRecords.push(
    ...newFraudFlags.map((fraudFlag) =>
      createTransferAudit({
        eventId: input.event.id,
        ticketId: input.ticket.id,
        action: 'fraud_flagged',
        actorUserId: input.sellerId,
        listingId,
        metadata: {
          fraudFlagId: fraudFlag.id,
          category: fraudFlag.category,
        },
        now,
      }),
    ),
  );

  return {
    ticket: nextTicket,
    listing,
    auditRecords,
    fraudFlags: eligibility.fraudFlags,
  };
}

/**
 * Settles a resale purchase and produces an auditable payout split ledger.
 */
export function buyResaleTicket(input: BuyResaleTicketInput): BuyResaleTicketResult {
  const now = input.now ?? Date.now();

  if (input.listing.status !== 'active') {
    throw new Error('Listing is no longer available');
  }

  if (input.listing.approvalStatus === 'pending') {
    throw new Error('Listing is pending organizer approval');
  }

  if (input.listing.sellerId === input.buyerId) {
    throw new Error('Seller cannot buy their own resale listing');
  }

  const eligibility = computeTransferEligibility({
    event: input.event,
    ticket: input.ticket,
    actorUserId: input.listing.sellerId,
    auditLog: input.marketplace.auditLog,
    fraudFlags: input.marketplace.fraudFlags,
    now,
  });

  if (eligibility.blockedReasons.length > 0) {
    throw new Error(eligibility.blockedReasons[0]);
  }

  const payoutSplits = buildPayoutSplits({
    event: input.event,
    ticket: input.ticket,
    listing: input.listing,
    now,
  });
  const nextTicket = executeTransfer({
    ticket: input.ticket,
    nextOwnerId: input.buyerId,
    nextOwnerWallet: input.buyerWallet,
    reason: 'resale_purchase',
    now,
  });
  const nextListing: ResaleListingRecord = {
    ...input.listing,
    status: 'sold',
    approvalStatus:
      input.listing.approvalStatus === 'approved' ? 'approved' : input.listing.approvalStatus,
    updatedAt: now,
    soldAt: now,
    buyerId: input.buyerId,
  };

  const auditRecords = [
    createTransferAudit({
      eventId: input.event.id,
      ticketId: input.ticket.id,
      action: 'resale_purchased',
      actorUserId: input.buyerId,
      subjectUserId: input.listing.sellerId,
      listingId: input.listing.id,
      payoutSplitIds: payoutSplits.map((split) => split.id),
      metadata: {
        salePrice: input.listing.askPrice.toFixed(2),
        sellerId: input.listing.sellerId,
      },
      now,
    }),
    ...payoutSplits.map((split) =>
      createTransferAudit({
        eventId: split.eventId,
        ticketId: split.ticketId,
        action: 'royalty_recorded',
        actorUserId: input.buyerId,
        subjectUserId: split.recipientUserId,
        listingId: split.listingId,
        payoutSplitIds: [split.id],
        metadata: {
          recipientType: split.recipientType,
          amount: split.amount.toFixed(2),
          basisPoints: String(split.basisPoints),
        },
        now,
      }),
    ),
  ];

  const newFraudFlags = eligibility.fraudFlags.slice(input.marketplace.fraudFlags.length);
  auditRecords.push(
    ...newFraudFlags.map((fraudFlag) =>
      createTransferAudit({
        eventId: input.event.id,
        ticketId: input.ticket.id,
        action: 'fraud_flagged',
        actorUserId: input.buyerId,
        listingId: input.listing.id,
        metadata: {
          fraudFlagId: fraudFlag.id,
          category: fraudFlag.category,
        },
        now,
      }),
    ),
  );

  return {
    ticket: nextTicket,
    listing: nextListing,
    payoutSplits,
    auditRecords,
    fraudFlags: eligibility.fraudFlags,
  };
}

function validateResalePrice(
  event: EventRecord,
  ticket: TicketRecord,
  salePrice: number,
  now: number,
): number {
  if (!Number.isFinite(salePrice) || salePrice <= 0) {
    throw new Error('Resale price must be greater than zero');
  }

  const policy = resolveEventMarketplaceSettings(event).policy;
  const minPrice = roundCurrency(ticket.purchasePrice * policy.minPriceMultiplier);
  const multiplierMaxPrice = roundCurrency(ticket.purchasePrice * policy.maxPriceMultiplier);
  const dynamicLimit = calculateResaleLimit(
    ticket.purchasePrice,
    event.eventDate,
    event.resaleConfig ?? defaultAppSettings,
  );
  const maxPrice = Math.min(multiplierMaxPrice, roundCurrency(dynamicLimit.maxPrice));

  if (salePrice < minPrice) {
    throw new Error(`Resale price must be at least ${minPrice.toFixed(2)}`);
  }

  if (salePrice > maxPrice) {
    throw new Error(`Resale price exceeds max allowed price of ${maxPrice.toFixed(2)}`);
  }

  if (event.eventDate <= now) {
    throw new Error('Resale is closed after the event start time');
  }

  return roundCurrency(salePrice);
}

function buildPayoutSplits(input: {
  event: EventRecord;
  ticket: TicketRecord;
  listing: ResaleListingRecord;
  now: number;
}): PayoutSplitRecord[] {
  const policy = resolveEventMarketplaceSettings(input.event).policy;
  const platformFeeBasisPoints = Math.max(
    0,
    Math.round((input.event.resaleConfig.platformFeePercent ?? defaultAppSettings.platformFeePercent) * 100),
  );
  const royaltyAmount = roundCurrency(input.listing.askPrice * (policy.royaltyBasisPoints / 10_000));
  const platformFeeAmount = roundCurrency(input.listing.askPrice * (platformFeeBasisPoints / 10_000));
  const sellerBasisPoints = Math.max(0, 10_000 - policy.royaltyBasisPoints - platformFeeBasisPoints);
  const sellerAmount = roundCurrency(input.listing.askPrice - royaltyAmount - platformFeeAmount);
  const splits: PayoutSplitRecord[] = [
    {
      id: `split_${input.now}_${Math.random().toString(36).slice(2, 8)}`,
      listingId: input.listing.id,
      ticketId: input.ticket.id,
      eventId: input.event.id,
      recipientType: 'seller',
      recipientUserId: input.listing.sellerId,
      recipientWallet: input.listing.sellerWallet,
      grossAmount: input.listing.askPrice,
      amount: sellerAmount,
      currency: input.listing.currency,
      basisPoints: sellerBasisPoints,
      createdAt: input.now,
    },
    {
      id: `split_${input.now}_${Math.random().toString(36).slice(2, 8)}`,
      listingId: input.listing.id,
      ticketId: input.ticket.id,
      eventId: input.event.id,
      recipientType: 'organizer_royalty',
      recipientUserId: input.event.organizerId,
      recipientWallet: input.event.organizerWallet ?? null,
      grossAmount: input.listing.askPrice,
      amount: royaltyAmount,
      currency: input.listing.currency,
      basisPoints: policy.royaltyBasisPoints,
      createdAt: input.now,
    },
  ];

  if (platformFeeAmount > 0) {
    splits.push({
      id: `split_${input.now}_${Math.random().toString(36).slice(2, 8)}`,
      listingId: input.listing.id,
      ticketId: input.ticket.id,
      eventId: input.event.id,
      recipientType: 'platform_fee',
      recipientUserId: null,
      recipientWallet: null,
      grossAmount: input.listing.askPrice,
      amount: platformFeeAmount,
      currency: input.listing.currency,
      basisPoints: platformFeeBasisPoints,
      createdAt: input.now,
    });
  }

  return splits;
}

function roundCurrency(value: number): number {
  return Math.round(value * 100) / 100;
}
